services:
  - type: web
    name: flexliving-reviews
    env: docker
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/reviews-1.0.0.jar"
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
    ports:
      - 8080
